CREATE TABLE `TABLE_NAME_PLACEHOLDER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `RECORD_ID` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `REF_KEY` varchar(300) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `NAME` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `REC_CREATION_TMSTP` timestamp NULL DEFAULT NULL,
  `REC_MODIFIED_TMSTP` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `idx_TABLE_NAME_PLACEHOLDER_RECORD_ID` (`RECORD_ID`),
  KEY `idx_TABLE_NAME_PLACEHOLDER_REF_KEY` (`REF_KEY`)
) ENGINE=InnoDB;
