CREATE TABLE `TABLE_NAME_PLACEHOLDER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DOCUMENT_ID` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `LOCALE` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `RECORD_ID` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `REF_KEY` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `NAME` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `REC_CREATION_TMSTP` timestamp NULL DEFAULT NULL,
  `REC_MODIFIED_TMSTP` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `idx_TABLE_NAME_PLACEHOLDER_RECORD_ID` (`RECORD_ID`),
  KEY `idx_TABLE_NAME_PLACEHOLDER_DOCUMENT_ID` (`DOCUMENT_ID`),
  KEY `idx_TABLE_NAME_PLACEHOLDER_LOCALE` (`LOCALE`),
  KEY `idx_TABLE_NAME_PLACEHOLDER_REF_KEY` (`REF_KEY`)
) ENGINE=InnoDB;
